name: tinhocstar
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Sử dụng phiên bản mới nhất tương thích
  cupertino_icons: ^1.0.2
  gsheets: ^0.5.0
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  crypto: ^3.0.3
  http: ^1.2.1
  file_picker: ^8.0.0+1
  flutter_secure_storage: ^9.0.0 # Thêm thư viện này nếu bạn dùng trong code mới

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
