# Xác định vị trí thư mục gốc của dự án Flutter
flutter_project_path = File.expand_path('..', __dir__)

# Nạp các biến môi trường từ các file do Flutter tạo ra
load File.join(flutter_project_path, '.ios', 'Flutter', 'Generated.xcconfig')

# Xác định các thư viện mà Flutter cần từ các plugin
require_relative File.join(flutter_project_path, '.ios', 'Flutter', 'podhelper.rb')

# Định nghĩa nền tảng mục tiêu
platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Cài đặt tất cả các thư viện được định nghĩa bởi các plugin Flutter
  install_all_flutter_pods(flutter_project_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Ép tất cả các thư viện phụ phải tuân thủ phiên bản iOS 13.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
