# CocoaPods-managed Xcode project for the Runner target.
#
# This file is created by Flutter.
# To learn more, see: https://flutter.dev/go/ios-project-structure.

platform :ios, '13.0' # <-- YÊU CẦU PHIÊN BẢN TỐI THIỂU

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # --> ĐOẠN CODE "ÉP" PHIÊN BẢN CHO TẤT CẢ THƯ VIỆN PHỤ
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    # <-- KẾT THÚC ĐOẠN CODE "ÉP"
  end
end

flutter_application_path = File.join(File.dirname(__FILE__), '..')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
